name: Build and Test
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab #v3.5.2
    - name: Tests
      run: ./bin/test.sh
    - name: Build
      run: ./bin/build.sh
